"""Centralized configuration for the PPE Safety Detector."""

from pathlib import Path

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
PROJECT_ROOT = Path(__file__).resolve().parent.parent
MODEL_DIR = PROJECT_ROOT / "models"
YOLO_WEIGHTS = MODEL_DIR / "yolov8n.pt"          # swap with custom-trained weights
ONNX_WEIGHTS = MODEL_DIR / "yolov8n.onnx"        # generated by export_onnx.py
VIOLATION_LOG = PROJECT_ROOT / "violations.csv"

# ---------------------------------------------------------------------------
# Detection classes
# ---------------------------------------------------------------------------
# Class IDs produced by the model. Update these when using a custom-trained
# model whose class order differs from the COCO-pretrained YOLOv8n defaults.
#
# For a custom PPE dataset the mapping would look like:
#   PPE_CLASSES = {0: "helmet", 1: "vest", 2: "gloves"}
#   PERSON_CLASS_ID = 3  # or whatever index "person" has in your dataset
#
# With the stock COCO model we approximate PPE items via visually similar
# COCO classes so the pipeline can be demonstrated end-to-end without
# requiring a custom dataset.
PERSON_CLASS_ID = 0  # COCO: "person"

# COCO proxies used for demo purposes — replace with real PPE class IDs
PPE_CLASSES: dict[int, str] = {
    # Custom PPE model example (uncomment and adjust):
    # 0: "helmet",
    # 1: "vest",
    # 2: "gloves",

    # COCO proxies for demonstration:
    25: "helmet",     # COCO "umbrella" as helmet stand-in
    27: "vest",       # COCO "backpack" as vest stand-in
    64: "gloves",     # COCO "mouse" as gloves stand-in
}

REQUIRED_PPE: set[str] = {"helmet", "vest"}

# ---------------------------------------------------------------------------
# Detection thresholds
# ---------------------------------------------------------------------------
CONFIDENCE_THRESHOLD = 0.45
IOU_THRESHOLD = 0.50
PPE_ASSOCIATION_IOU = 0.30  # min IoU to associate a PPE box with a person

# ---------------------------------------------------------------------------
# Alert timing
# ---------------------------------------------------------------------------
VIOLATION_HOLD_SEC = 2.0  # seconds without PPE before alert triggers

# ---------------------------------------------------------------------------
# Display
# ---------------------------------------------------------------------------
COLOR_COMPLIANT = (0, 200, 0)       # BGR green
COLOR_VIOLATION = (0, 0, 220)       # BGR red
COLOR_TEXT_BG = (30, 30, 30)        # dark background for text
FONT_SCALE = 0.55
BORDER_THICKNESS = 3
